export const TEST_SUITES = Object.freeze({
  fast: Object.freeze([
    "activityIdeSession.test.mjs",
    "arduinoCompiler.test.mjs",
    "bleProtocol.test.mjs",
    "bleProtocolV3.test.mjs",
    "bleRunProtocol.test.mjs",
    "bleUpdateProgress.test.mjs",
    "bluetoothTransport.test.mjs",
    "byteQueue.test.mjs",
    "confirmClassroomPersistence.test.mjs",
    "courseActivityApi.test.mjs",
    "courseInvites.test.mjs",
    "courseMembers.test.mjs",
    "courseRole.test.mjs",
    "courseRosterPending.test.mjs",
    "micropythonFeatureFlags.test.mjs",
    "orgRole.test.mjs",
    "orgRoleMulti.test.mjs",
    "platformRole.test.mjs",
    "platformSchoolCycle.test.mjs",
    "pybotClassCourseRoles.test.mjs",
    "pybotclassI18n.test.mjs",
    "replProtocol.test.mjs",
    "studentCourses.test.mjs",
    "telemetry.test.mjs",
    "testSuiteManifest.test.mjs",
    "versionConsistency.test.mjs",
  ]),
  contracts: Object.freeze([
    "bleDeploySession.test.mjs",
    "bleNativeBackend.test.mjs",
    "bleRunSession.test.mjs",
    "bleRunStop.test.mjs",
    "bleRuntimeUpdateProtocol.test.mjs",
    "bleRuntimeUpdateSession.test.mjs",
    "eda6Adc2WifiWarning.test.mjs",
    "eda6InputPath.test.mjs",
    "eda6ServoHold.test.mjs",
    "eda6UsbImport.test.mjs",
    "esp32BoardProbe.test.mjs",
    "esp32FirmwareManifest.test.mjs",
    "esp32Flasher.test.mjs",
    "esp32HardwareReset.test.mjs",
    "esp32InstallManifest.test.mjs",
    "esp32Provisioning.test.mjs",
    "esp32SerialGpio.test.mjs",
    "firmwareAppLifecycle.test.mjs",
    "firmwareAppStopForce.test.mjs",
    "firmwareBootUpdate.test.mjs",
    "firmwareCompileall.test.mjs",
    "firmwareRunRerun.test.mjs",
    "hardwareBridgeSerialPriority.test.mjs",
    "immutableSubmissionVersions.test.mjs",
    "micropythonNativeBle.test.mjs",
    "micropythonNetwork.test.mjs",
    "micropythonPortOpenBusy.test.mjs",
    "micropythonSession.test.mjs",
    "platformSchoolMigrations.test.mjs",
    "reliableBleTransport.test.mjs",
    "runtimeRelease407.test.mjs",
  ]),
  architecture: Object.freeze([
    "activityIdentity.test.mjs",
    "activityMetaPersist.test.mjs",
    "bleClearAppUsb.test.mjs",
    "bleRuntimeModular.test.mjs",
    "bleStopUiPath.test.mjs",
    "classifyClassroomConnection.test.mjs",
    "classroomIdentitySeparation.test.mjs",
    "documentIntegrity.test.mjs",
    "entryI18n.test.mjs",
    "esp32ProvisioningWiring.test.mjs",
    "memoryDiagnostic.test.mjs",
    "micropythonArchitecture.test.mjs",
    "pybotclass.test.mjs",
    "pybotclassWorkflow.test.mjs",
  ]),
});

export function filesForSuite(name) {
  if (name === "full") {
    return [...TEST_SUITES.fast, ...TEST_SUITES.contracts, ...TEST_SUITES.architecture];
  }
  const files = TEST_SUITES[name];
  if (!files) {
    throw new Error(`Unknown test suite: ${name}`);
  }
  return [...files];
}
