/**
 * Máquina de estados del flujo Preparar ESP32.
 * Un solo `phase` (no un mar de booleanos) describe la UI y la cancelación.
 */

export const PHASE = Object.freeze({
  IDLE: "IDLE",
  SELECTING_PORT: "SELECTING_PORT",
  PROBING: "PROBING",
  ALREADY_PREPARED: "ALREADY_PREPARED",
  CONFIRM_FLASH: "CONFIRM_FLASH",
  CONFIRM_INSTALL: "CONFIRM_INSTALL",
  CONFIRM_UPDATE: "CONFIRM_UPDATE",
  CONFIRM_REINSTALL: "CONFIRM_REINSTALL",
  CONNECTING_BOOTLOADER: "CONNECTING_BOOTLOADER",
  NEED_BOOT_BUTTON: "NEED_BOOT_BUTTON",
  IDENTIFYING_CHIP: "IDENTIFYING_CHIP",
  UNSUPPORTED_VARIANT: "UNSUPPORTED_VARIANT",
  LOADING_FIRMWARE: "LOADING_FIRMWARE",
  VERIFYING_IMAGE_HASH: "VERIFYING_IMAGE_HASH",
  ERASING: "ERASING",
  FLASHING: "FLASHING",
  VERIFYING_FLASH: "VERIFYING_FLASH",
  FLASH_WRITTEN: "FLASH_WRITTEN",
  RESETTING: "RESETTING",
  WAITING_REPL: "WAITING_REPL",
  RESET_REQUIRED: "RESET_REQUIRED",
  INSTALLING_PYBOT: "INSTALLING_PYBOT",
  VERIFYING_FILES: "VERIFYING_FILES",
  RESETTING_PYBOT: "RESETTING_PYBOT",
  READY: "READY",
  ERROR: "ERROR",
  CANCELLED: "CANCELLED",
});

export const BOARD_STATE = Object.freeze({
  VIRGIN: "VIRGIN",
  MICROPYTHON_ONLY: "MICROPYTHON_ONLY",
  MPY_ONLY: "MICROPYTHON_ONLY",
  INCOMPLETE: "INCOMPLETE",
  OLD_PYBOT: "OLD_PYBOT",
  READY: "READY",
  INCOMPATIBLE_MPY: "INCOMPATIBLE_MPY",
  REPL_UNAVAILABLE: "REPL_UNAVAILABLE",
  PORT_BUSY: "PORT_BUSY",
  RESET_REQUIRED: "RESET_REQUIRED",
  UNKNOWN: "UNKNOWN",
});

/** Fases en las que cerrar el modal / abortar dejaría la placa a medias. */
export const CRITICAL_PHASES = Object.freeze([
  PHASE.ERASING,
  PHASE.FLASHING,
  PHASE.VERIFYING_FLASH,
]);

export function isCriticalPhase(phase) {
  return CRITICAL_PHASES.includes(phase);
}

export function canCloseModal(phase) {
  return !isCriticalPhase(phase);
}

export const PROVISION_ERROR = Object.freeze({
  PORT_CANCELLED: "PORT_CANCELLED",
  PORT_PERMISSION: "PORT_PERMISSION",
  BUSY: "BUSY",
  BOOTLOADER_FAIL: "BOOTLOADER_FAIL",
  VARIANT_UNSUPPORTED: "VARIANT_UNSUPPORTED",
  FIRMWARE_FETCH_FAIL: "FIRMWARE_FETCH_FAIL",
  FIRMWARE_HASH_MISMATCH: "FIRMWARE_HASH_MISMATCH",
  ERASE_FAIL: "ERASE_FAIL",
  FLASH_FAIL: "FLASH_FAIL",
  FLASH_VERIFY_FAIL: "FLASH_VERIFY_FAIL",
  RESET_FAIL: "RESET_FAIL",
  REPL_TIMEOUT: "REPL_TIMEOUT",
  RESET_REQUIRED: "RESET_REQUIRED",
  REPL_UNAVAILABLE: "REPL_UNAVAILABLE",
  INSTALL_FAIL: "INSTALL_FAIL",
  VERIFY_FILES_FAIL: "VERIFY_FILES_FAIL",
  CANCELLED: "CANCELLED",
  UNKNOWN: "UNKNOWN",
});
