/** Ejemplos async para PyBot-Web */

export const DEFAULT_CODE = [
  'async def main():',
  '    print("PyBot Web — conectá USB y ejecutá")',
  "    await motor(10, 50)",
  "    await wait(1)",
  "    await motor(10, 0)",
  "",
  "import asyncio",
  "asyncio.run(main())",
  "",
].join("\n");

export const EXAMPLES = [
  {
    id: "blink",
    keyEs: "Blink",
    keyEn: "Blink",
    file: "blink.py",
    code: [
      "async def main():",
      "    while True:",
      '        await pin("out", 2, 1)',
      "        await wait(0.5)",
      '        await pin("out", 2, 0)',
      "        await wait(0.5)",
      "",
      "import asyncio",
      "asyncio.run(main())",
      "",
    ].join("\n"),
  },
  {
    id: "motor",
    keyEs: "Motor",
    keyEn: "Motor",
    file: "motor.py",
    code: [
      "async def main():",
      "    await motor(10, 80)",
      "    await wait(2)",
      "    await motor(10, -60)",
      "    await wait(2)",
      "    await motor(10, 0)",
      "",
      "import asyncio",
      "asyncio.run(main())",
      "",
    ].join("\n"),
  },
  {
    id: "servo",
    keyEs: "Servo",
    keyEn: "Servo",
    file: "servo.py",
    code: [
      "async def main():",
      "    await servo(10, 0)",
      "    await wait(1)",
      "    await servo(10, 90)",
      "    await wait(1)",
      "    await servo(10, 180)",
      "",
      "import asyncio",
      "asyncio.run(main())",
      "",
    ].join("\n"),
  },
  {
    id: "light_sensor",
    keyEs: "Sensor de luz",
    keyEn: "Light sensor",
    file: "light_sensor.py",
    code: [
      "async def main():",
      "    for _ in range(20):",
      '        luz = await pin("in", "A0")',
      "        pct = int(luz / 1023 * 100)",
      '        print(f"Luz: {pct}%")',
      "        await wait(0.3)",
      "",
      "import asyncio",
      "asyncio.run(main())",
      "",
    ].join("\n"),
  },
  {
    id: "button",
    keyEs: "Pulsador",
    keyEn: "Button",
    file: "button.py",
    code: [
      "async def main():",
      "    while True:",
      '        if await pin("in", 7):',
      '            await pin("out", 2, 1)',
      "        else:",
      '            await pin("out", 2, 0)',
      "        await wait(0.05)",
      "",
      "import asyncio",
      "asyncio.run(main())",
      "",
    ].join("\n"),
  },
];
