/** Ejemplos estilo PyBot escritorio (sin bloque main()). */

export const DEFAULT_CODE = [
  'print("PyBot Web listo.")',
  "# Si activás Solo Python, podés usar Python puro sin Arduino.",
  "",
  "for i in range(5):",
  '    print("Linea", i)',
  "    wait(0.2)",
  "",
].join("\n");

export const EXAMPLES = [
  {
    id: "python_hello",
    keyEs: "Python: Hola",
    keyEn: "Python: Hello",
    file: "python_hello.py",
    code: [
      'print("Hola desde PyBot Web")',
      "for i in range(1, 6):",
      '    print("Contador:", i)',
    ].join("\n"),
  },
  {
    id: "python_tables",
    keyEs: "Python: Tabla",
    keyEn: "Python: Table",
    file: "python_table.py",
    code: [
      "n = 7",
      'print(f"Tabla del {n}")',
      "for i in range(1, 11):",
      '    print(f"{n} x {i} = {n*i}")',
    ].join("\n"),
  },
  {
    id: "python_functions",
    keyEs: "Python: Funciones",
    keyEn: "Python: Functions",
    file: "python_functions.py",
    code: [
      "def saludar(nombre):",
      '    return f"Hola, {nombre}!"',
      "",
      'nombres = ["Ana", "Leo", "Mia"]',
      "for n in nombres:",
      "    print(saludar(n))",
    ].join("\n"),
  },
  {
    id: "python_lists",
    keyEs: "Python: Listas",
    keyEn: "Python: Lists",
    file: "python_lists.py",
    code: [
      "nums = [5, 1, 8, 3, 2]",
      'print("Original:", nums)',
      "nums.sort()",
      'print("Ordenada:", nums)',
      'print("Suma:", sum(nums))',
      'print("Promedio:", sum(nums)/len(nums))',
    ].join("\n"),
  },
  {
    id: "python_while_input",
    keyEs: "Python: While + Input",
    keyEn: "Python: While + Input",
    file: "while_input.py",
    code: [
      "total = 0",
      "cantidad = 0",
      "",
      "while True:",
      '    nota = input("Ingresa una nota (o \'salir\'): ")',
      '    if nota.strip().lower() == "salir":',
      "        break",
      "    n = float(nota)",
      "    if n < 0 or n > 10:",
      '        print("La nota debe estar entre 0 y 10")',
      "        continue",
      "    total = total + n",
      "    cantidad = cantidad + 1",
      '    print(f"  Nota {cantidad}: {n}")',
      "",
      "if cantidad > 0:",
      "    promedio = total / cantidad",
      '    print(f"\\nNotas ingresadas: {cantidad}")',
      '    print(f"Promedio: {promedio:.1f}")',
      "    if promedio >= 7:",
      '        print("Resultado: APROBADO")',
      "    else:",
      '        print("Resultado: debe mejorar")',
      "else:",
      '    print("No se ingresaron notas.")',
    ].join("\n"),
  },
  {
    id: "canvas_demo",
    keyEs: "Canvas: Demo completa",
    keyEn: "Canvas: Full demo",
    file: "canvas_demo.py",
    code: [
      "# screen(width, height) - create canvas",
      "screen(400, 300)",
      "",
      "# fill(color) - paint entire background",
      'fill("black")',
      "",
      "# draw_rect(x, y, width, height, color)",
      'draw_rect(10, 10, 120, 60, "red")',
      'draw_rect(10, 80, 120, 60, "blue")',
      "",
      "# draw_circle(x, y, radius, color)",
      'draw_circle(200, 40, 30, "green")',
      'draw_circle(200, 110, 30, "yellow")',
      "",
      "# draw_line(x1, y1, x2, y2, color, width)",
      'draw_line(280, 10, 390, 10, "purple", 2)',
      'draw_line(280, 30, 390, 30, "orange", 4)',
      'draw_line(280, 50, 390, 50, "cyan", 6)',
      "",
      "# draw_text(x, y, message, color, font_size)",
      'draw_text(10, 160, "PyBot Canvas", "white", 28)',
      'draw_text(10, 195, "All drawing functions", "gray", 14)',
      "",
      "# Art with loops",
      "for i in range(12):",
      '    draw_circle(60 + i * 28, 240, 10, "pink")',
      "",
      "# Colors accept: names, spanish names, or HEX",
      'draw_rect(10, 265, 380, 25, "#1a1a2e")',
      'draw_text(20, 268, "HEX colors: #ff6600 #3498db", "#ff6600", 12)',
      "",
      "# flip() - display the frame (double buffered)",
      "flip()",
      "",
      "# clear() - erase everything",
      "# key_pressed(key_name) - True if key is held",
      "#   keys: up, down, left, right, space, w, a, s, d",
      "",
      'print("Canvas demo: all functions OK")',
    ].join("\n"),
  },
  {
    id: "canvas_pong",
    keyEs: "Canvas: Pong",
    keyEn: "Canvas: Pong",
    file: "pong.py",
    code: [
      "# PONG - Player vs AI",
      "# Arrow UP / DOWN to move your paddle",
      "screen(400, 300)",
      "",
      "ball_x = 200",
      "ball_y = 150",
      "vel_x = 3",
      "vel_y = 2",
      "player_y = 120",
      "ai_y = 120",
      "paddle_h = 50",
      "score_p = 0",
      "score_ai = 0",
      "",
      "for frame in range(2000):",
      '    if key_pressed("up"):',
      "        player_y = max(player_y - 5, 0)",
      '    if key_pressed("down"):',
      "        player_y = min(player_y + 5, 250)",
      "",
      "    if ball_y > ai_y + 25:",
      "        ai_y = min(ai_y + 3, 250)",
      "    elif ball_y < ai_y + 20:",
      "        ai_y = max(ai_y - 3, 0)",
      "",
      "    ball_x += vel_x",
      "    ball_y += vel_y",
      "",
      "    if ball_y <= 5: vel_y = abs(vel_y)",
      "    if ball_y >= 290: vel_y = -abs(vel_y)",
      "    if ball_x <= 20 and player_y <= ball_y <= player_y + paddle_h:",
      "        vel_x = abs(vel_x)",
      "    if ball_x >= 375 and ai_y <= ball_y <= ai_y + paddle_h:",
      "        vel_x = -abs(vel_x)",
      "",
      "    if ball_x < 0:",
      "        score_ai += 1",
      "        ball_x, ball_y, vel_x = 200, 150, 3",
      "    if ball_x > 400:",
      "        score_p += 1",
      "        ball_x, ball_y, vel_x = 200, 150, -3",
      "",
      '    fill("black")',
      "    for i in range(15):",
      '        draw_rect(198, i * 20 + 2, 4, 12, "gray")',
      '    draw_rect(10, int(player_y), 8, paddle_h, "blue")',
      '    draw_rect(382, int(ai_y), 8, paddle_h, "red")',
      '    draw_circle(int(ball_x), int(ball_y), 6, "white")',
      '    draw_text(130, 10, f"YOU: {score_p}", "blue", 22)',
      '    draw_text(240, 10, f"AI: {score_ai}", "red", 22)',
      "    flip()",
      "",
      "    if score_p >= 5 or score_ai >= 5: break",
      "",
      'fill("black")',
      'draw_rect(100, 100, 200, 100, "#1a1a2e")',
      "if score_p > score_ai:",
      '    draw_text(110, 120, "YOU WIN!", "blue", 32)',
      "else:",
      '    draw_text(110, 120, "AI WINS!", "red", 32)',
      'draw_text(130, 165, f"{score_p} - {score_ai}", "white", 24)',
      "flip()",
    ].join("\n"),
  },
  {
    id: "blink",
    keyEs: "Blink",
    keyEn: "Blink",
    file: "blink.py",
    code: [
      "while True:",
      '    pin("out", 2, 1)',
      "    wait(0.5)",
      '    pin("out", 2, 0)',
      "    wait(0.5)",
    ].join("\n"),
  },
  {
    id: "motor",
    keyEs: "Motor",
    keyEn: "Motor",
    file: "motor.py",
    code: [
      "motor(10, 80)",
      "wait(2)",
      "motor(10, -60)",
      "wait(2)",
      "motor(10, 0)",
    ].join("\n"),
  },
  {
    id: "servo",
    keyEs: "Servo",
    keyEn: "Servo",
    file: "servo.py",
    code: [
      "servo(10, 0)",
      "wait(1)",
      "servo(10, 90)",
      "wait(1)",
      "servo(10, 180)",
    ].join("\n"),
  },
  {
    id: "light_sensor",
    keyEs: "Sensor de luz",
    keyEn: "Light sensor",
    file: "light_sensor.py",
    code: [
      "for _ in range(20):",
      '    luz = pin("in", "A0")',
      "    pct = int(luz / 1023 * 100)",
      '    print(f"Luz: {pct}%")',
      "    wait(0.3)",
    ].join("\n"),
  },
  {
    id: "button",
    keyEs: "Pulsador",
    keyEn: "Button",
    file: "button.py",
    code: [
      "while True:",
      '    if pin("in", 7):',
      '        pin("out", 2, 1)',
      "    else:",
      '        pin("out", 2, 0)',
      "    wait(0.05)",
    ].join("\n"),
  },
  {
    id: "arduino_standalone_traffic",
    keyEs: "Arduino solo: Semaforo",
    keyEn: "Arduino standalone: Traffic light",
    file: "arduino_standalone_traffic.py",
    code: [
      "# Probalo en vivo y luego usa 'Bajar a Arduino' para que",
      "# funcione solo, desconectado de la PC. LEDs en pines 2, 3 y 4.",
      "while True:",
      '    pin("out", 4, 1)',
      "    wait(2)",
      '    pin("out", 4, 0)',
      '    pin("out", 3, 1)',
      "    wait(1)",
      '    pin("out", 3, 0)',
      '    pin("out", 2, 1)',
      "    wait(2)",
      '    pin("out", 2, 0)',
    ].join("\n"),
  },
  {
    id: "arduino_standalone_breath",
    keyEs: "Arduino solo: Latido (PWM)",
    keyEn: "Arduino standalone: Breathing (PWM)",
    file: "arduino_standalone_breath.py",
    code: [
      "# LED con resistencia en el pin 9 (PWM).",
      "# Funciona en vivo y tambien al 'Bajar a Arduino'.",
      "while True:",
      "    for v in range(0, 256, 15):",
      '        pin("pwm", 9, v)',
      "        wait(0.03)",
      "    for v in range(255, -1, -15):",
      '        pin("pwm", 9, v)',
      "        wait(0.03)",
    ].join("\n"),
  },
  {
    id: "esp32_blink",
    keyEs: "ESP32: Blink",
    keyEn: "ESP32: Blink",
    file: "esp32_blink.py",
    code: [
      "# ESP32: requiere el firmware PyBot ESP32 y la placa ESP32 seleccionada.",
      "# Se usa el numero de GPIO directo. El LED onboard suele estar en GPIO 2.",
      "while True:",
      '    pin("out", 2, 1)',
      "    wait(0.5)",
      '    pin("out", 2, 0)',
      "    wait(0.5)",
    ].join("\n"),
  },
  {
    id: "esp32_digital_in",
    keyEs: "ESP32: Lectura digital",
    keyEn: "ESP32: Digital read",
    file: "esp32_digital_in.py",
    code: [
      "# ESP32: pulsador en GPIO 4, LED en GPIO 2 (numero de GPIO directo).",
      "while True:",
      '    if pin("in", 4):',
      '        pin("out", 2, 1)',
      "    else:",
      '        pin("out", 2, 0)',
      "    wait(0.05)",
    ].join("\n"),
  },
  {
    id: "esp32_analog_in",
    keyEs: "ESP32: Lectura analógica",
    keyEn: "ESP32: Analog read",
    file: "esp32_analog_in.py",
    code: [
      "# ESP32: lectura analogica en GPIO 34 (prefijo A + numero de GPIO).",
      "# El valor llega escalado 0-1023, igual que en Arduino.",
      "for _ in range(20):",
      '    valor = pin("in", "A34")',
      "    pct = int(valor / 1023 * 100)",
      '    print(f"Sensor: {pct}%")',
      "    wait(0.3)",
    ].join("\n"),
  },
  {
    id: "esp32_pwm",
    keyEs: "ESP32: PWM",
    keyEn: "ESP32: PWM",
    file: "esp32_pwm.py",
    code: [
      "# ESP32: PWM en GPIO 18 (brillo de un LED). Valor 0-255.",
      "for v in range(0, 256, 15):",
      '    pin("pwm", 18, v)',
      "    wait(0.05)",
      "for v in range(255, -1, -15):",
      '    pin("pwm", 18, v)',
      "    wait(0.05)",
      'pin("pwm", 18, 0)',
    ].join("\n"),
  },
  {
    id: "eda6_servo",
    keyEs: "EDA6: Servo puerto 1",
    keyEn: "EDA6: Servo port 1",
    file: "eda6_servo.py",
    boards: ["esp32-eda6"],
    code: [
      "from EDA6 import *",
      "from time import sleep",
      "",
      'print("Probando servo en puerto 1")',
      "",
      "while True:",
      '    print("Servo puerto 1 a 0 grados")',
      "    servomotor(1, 0)",
      "    sleep(2)",
      "",
      '    print("Servo puerto 1 a 90 grados")',
      "    servomotor(1, 90)",
      "    sleep(2)",
      "",
      '    print("Servo puerto 1 a 180 grados")',
      "    servomotor(1, 180)",
      "    sleep(2)",
      "",
      '    print("Servo puerto 1 vuelve a 90 grados")',
      "    servomotor(1, 90)",
      "    sleep(2)",
    ].join("\n"),
  },
  {
    id: "eda6_salida_digital",
    keyEs: "EDA6: Salida digital",
    keyEn: "EDA6: Digital output",
    file: "eda6_salida.py",
    boards: ["esp32-eda6"],
    code: [
      "from EDA6 import *",
      "from time import sleep",
      "",
      "while True:",
      "    salidaDigital(1, 1)",
      "    sleep(1)",
      "    salidaDigital(1, 0)",
      "    sleep(1)",
    ].join("\n"),
  },
  {
    id: "eda6_entrada_digital",
    keyEs: "EDA6: Entrada digital",
    keyEn: "EDA6: Digital input",
    file: "eda6_entrada_d.py",
    boards: ["esp32-eda6"],
    code: [
      "from EDA6 import *",
      "from time import sleep",
      "",
      "while True:",
      "    estado = entradaDigital(1)",
      '    print("Entrada digital 1:", estado)',
      "    salidaDigital(2, estado)",
      "    sleep(0.2)",
    ].join("\n"),
  },
  {
    id: "eda6_entrada_analogica",
    keyEs: "EDA6: Entrada analógica",
    keyEn: "EDA6: Analog input",
    file: "eda6_entrada_a.py",
    boards: ["esp32-eda6"],
    code: [
      "from EDA6 import *",
      "from time import sleep",
      "",
      "while True:",
      "    pct = entradaAnalogica(1)",
      '    print("Entrada analógica 1:", pct, "%")',
      "    sleep(0.5)",
    ].join("\n"),
  },
  {
    id: "eda6_motor_rc",
    keyEs: "EDA6: Motor RC",
    keyEn: "EDA6: RC motor",
    file: "eda6_motor.py",
    boards: ["esp32-eda6"],
    code: [
      "from EDA6 import *",
      "from time import sleep",
      "",
      "motorRC(1, 50)",
      "sleep(2)",
      "motorRC(1, -50)",
      "sleep(2)",
      "motorRC(1, 0)",
    ].join("\n"),
  },
  {
    id: "eda6_sensor_distancia",
    keyEs: "EDA6: Sensor distancia",
    keyEn: "EDA6: Distance sensor",
    file: "eda6_distancia.py",
    boards: ["esp32-eda6"],
    code: [
      "from EDA6 import *",
      "from time import sleep",
      "",
      "while True:",
      "    d = sensorDistancia(1)",
      '    print("Distancia puerto 1:", d, "cm")',
      "    sleep(0.5)",
    ].join("\n"),
  },
  {
    id: "eda6_lcd",
    keyEs: "EDA6: LCD básico",
    keyEn: "EDA6: Basic LCD",
    file: "eda6_lcd.py",
    boards: ["esp32-eda6"],
    code: [
      "from EDA6 import *",
      "from time import sleep",
      "",
      'limpiarLCD()',
      'printLCD(0, 0, "Hola EDA6")',
      'printLCD(0, 1, "PyBot Web")',
      "luzLCD(1)",
      "sleep(5)",
    ].join("\n"),
  },
  {
    id: "esp32_wifi_http",
    keyEs: "ESP32: Wi-Fi + HTTP",
    keyEn: "ESP32: Wi-Fi + HTTP",
    file: "esp32_wifi_http.py",
    boards: ["esp32-micropython", "esp32-eda6"],
    code: [
      'wifi_conectar("MiRed", "clave")',
      'print("IP:", wifi_ip())',
      'print("Estado:", wifi_estado())',
      'print("Senal:", wifi_signal())',
      "",
      'r = web_get("http://example.com")',
      "print(r.status)",
      "print(r.text[:200])",
    ].join("\n"),
  },
  {
    id: "esp32_google_sheets",
    keyEs: "ESP32: Google Sheets",
    keyEn: "ESP32: Google Sheets",
    file: "esp32_sheets.py",
    boards: ["esp32-micropython", "esp32-eda6"],
    code: [
      "# Reemplazá URL por tu Apps Script (ver docs/MICROPYTHON_NETWORK.md).",
      "# NO pongas claves reales en el codigo que compartis.",
      'URL = "https://script.google.com/macros/s/TU_SCRIPT_ID/exec"',
      "",
      'wifi_conectar("MiRed", "clave")',
      "",
      "datos = {",
      '    "temperatura": 24.5,',
      '    "humedad": 62.1,',
      '    "presion": 1012.9,',
      "}",
      "",
      "respuesta = web_post(URL, datos)",
      "print(respuesta.status)",
      "print(respuesta.text)",
    ].join("\n"),
  },
];
