export const HELP_COURSE = {
  es: {
    badge: "Ruta guiada",
    title: "Python desde cero (12-13) + bloque final de hardware",
    subtitle:
      "28 microlecciones para 16 clases: primero base solida en Python, luego hardware y proyecto final.",
    modules: [
      {
        id: "m1",
        title: "1) Fundamentos base",
        summary: "Arranque total: print, variables, tipos y lectura de errores.",
        lessons: [
          {
            id: "m1l1",
            title: "Tu primer programa util",
            duration: "12 min",
            objective: "Ejecutar codigo y entender como se muestra en la terminal.",
            steps: [
              "Escribe tres print con mensajes distintos.",
              "Ejecuta y revisa el orden de salida.",
              "Cambia un mensaje y vuelve a ejecutar para validar cambios.",
            ],
            challenge: "Muestra una mini presentacion de 4 lineas sobre vos.",
            tip: "Ejecutar, mirar salida y corregir rapido es un superpoder inicial.",
            code: 'print("Hola, curso de Python")\nprint("Me llamo Lucia")\nprint("Tengo 12 anios")\nprint("Hoy empiezo a programar")',
          },
          {
            id: "m1l2",
            title: "Variables: guardar informacion",
            duration: "14 min",
            objective: "Crear variables para evitar repetir datos.",
            steps: [
              "Declara nombre, edad y curso.",
              "Imprime una frase usando esas variables.",
              "Cambia los valores sin tocar el print final.",
            ],
            challenge: "Agrega una variable comida_favorita e imprimela tambien.",
            tip: "Una variable bien nombrada hace que el codigo se lea solo.",
            code: 'nombre = "Lucia"\nedad = 12\ncurso = "1A"\nprint("Soy", nombre, "de", curso, "y tengo", edad, "anios")',
          },
          {
            id: "m1l3",
            title: "Tipos de datos que vas a usar siempre",
            duration: "14 min",
            objective: "Diferenciar int, float, str y bool con ejemplos claros.",
            steps: [
              "Crea una variable de cada tipo.",
              "Imprime cada valor junto a type(valor).",
              "Compara resultados con un companero.",
            ],
            challenge: "Crea dos variables nuevas y adivina su tipo antes de ejecutar.",
            tip: "Si sabes el tipo de dato, sabes que operaciones se pueden hacer.",
            code: 'cantidad = 5\npromedio = 8.5\nmateria = "Robotica"\nactivo = True\nprint(type(cantidad), type(promedio), type(materia), type(activo))',
          },
          {
            id: "m1l4",
            title: "Errores comunes al empezar",
            duration: "10 min",
            objective: "Reconocer errores de sintaxis y corregirlos sin frustracion.",
            steps: [
              "Copia el codigo con un error de comillas.",
              "Ejecuta y lee el mensaje de error.",
              "Corrige y valida que ahora funciona.",
            ],
            challenge: "Provoca un error de parentesis y arreglalo.",
            tip: "El error no es castigo: es pista para mejorar.",
            code: 'print("Linea correcta")\n# print("Linea con error)\nprint("Si ves esto, ya lo corregiste")',
          },
        ],
      },
      {
        id: "m2",
        title: "2) Entrada, salida y operadores",
        summary: "Hablar con el usuario, convertir tipos y hacer cuentas con sentido.",
        lessons: [
          {
            id: "m2l1",
            title: "input + print: programas conversacionales",
            duration: "14 min",
            objective: "Recibir datos del usuario y responder con texto util.",
            steps: [
              "Pide nombre y deporte favorito con input.",
              "Guarda respuestas en variables.",
              "Muestra una frase personalizada.",
            ],
            challenge: "Pide tambien ciudad y arma una frase completa.",
            tip: "input siempre devuelve texto; luego podras convertirlo.",
            code: 'nombre = input("Tu nombre: ")\ndeporte = input("Deporte favorito: ")\nprint("Hola", nombre, "- hoy hablamos de", deporte)',
          },
          {
            id: "m2l2",
            title: "Conversion de tipos sin miedo",
            duration: "14 min",
            objective: "Usar int(), float() y str() para evitar errores de tipos.",
            steps: [
              "Pide dos numeros con input.",
              "Convierte ambos a int.",
              "Muestra suma y promedio.",
            ],
            challenge: "Calcula tambien la diferencia absoluta entre ambos.",
            tip: "Si olvidas convertir, el programa concatena texto en vez de sumar.",
            code: 'a = int(input("Numero 1: "))\nb = int(input("Numero 2: "))\nprint("Suma:", a + b)\nprint("Promedio:", (a + b) / 2)',
          },
          {
            id: "m2l3",
            title: "Operadores: aritmeticos, comparacion y logica",
            duration: "16 min",
            objective: "Aplicar + - * / y condiciones como >=, ==, and, or.",
            steps: [
              "Crea dos numeros y prueba operaciones basicas.",
              "Compara si uno es mayor que otro.",
              "Combina dos condiciones con and.",
            ],
            challenge: "Crea una regla para saber si puede jugar torneo (edad y permiso).",
            tip: "== compara valores; = asigna valores.",
            code: 'edad = 12\npermiso = True\nprint("doble edad:", edad * 2)\nprint("es mayor o igual a 12?", edad >= 12)\nprint("puede jugar torneo?", edad >= 12 and permiso)',
          },
        ],
      },
      {
        id: "m3",
        title: "3) Control de flujo",
        summary: "Tomar decisiones y repetir tareas sin copiar codigo.",
        lessons: [
          {
            id: "m3l1",
            title: "if y else para elegir caminos",
            duration: "14 min",
            objective: "Resolver una decision simple con dos salidas.",
            steps: [
              "Crea variable nota.",
              "Si nota >= 7 muestra 'Aprobado'.",
              "Si no, muestra 'A reforzar'.",
            ],
            challenge: "Cambia el limite y observa como cambia el resultado.",
            tip: "Despues de if y else va dos puntos y bloque con sangria.",
            code: 'nota = 8\nif nota >= 7:\n    print("Aprobado")\nelse:\n    print("A reforzar")',
          },
          {
            id: "m3l2",
            title: "elif para mas de dos opciones",
            duration: "16 min",
            objective: "Clasificar resultados en excelente, bien o revisar.",
            steps: [
              "Crea variable puntaje.",
              "Usa if/elif/else con tres categorias.",
              "Prueba con valores distintos.",
            ],
            challenge: "Agrega una cuarta categoria para puntaje perfecto.",
            tip: "Ordena condiciones de mayor a menor para evitar confusiones.",
            code: 'puntaje = 86\nif puntaje >= 90:\n    print("Excelente")\nelif puntaje >= 70:\n    print("Bien")\nelse:\n    print("A practicar")',
          },
          {
            id: "m3l3",
            title: "for con range para contar y generar patrones",
            duration: "16 min",
            objective: "Repetir una accion con numero de vueltas controlado.",
            steps: [
              "Usa range(1, 6).",
              "Imprime vuelta e indice.",
              "Cambia inicio y fin para ver diferencias.",
            ],
            challenge: "Muestra la tabla del 6 usando for.",
            tip: "range(1, 6) llega hasta 5, no incluye 6.",
            code: 'for i in range(1, 6):\n    print("Vuelta", i)\n\nfor i in range(1, 11):\n    print("6 x", i, "=", 6 * i)',
          },
          {
            id: "m3l4",
            title: "while, break, continue y pass (basico)",
            duration: "18 min",
            objective: "Controlar bucles con condiciones y cortes simples.",
            steps: [
              "Haz un contador con while.",
              "Usa continue para saltar un valor.",
              "Usa break para cortar al llegar a cierto punto.",
            ],
            challenge: "Cuenta del 1 al 10 y evita imprimir el 4.",
            tip: "Usa break con criterio para no dejar bucles infinitos.",
            code: 'n = 0\nwhile n < 10:\n    n += 1\n    if n == 4:\n        continue\n    if n == 9:\n        break\n    print(n)',
          },
        ],
      },
      {
        id: "m4",
        title: "4) Funciones y buenas practicas",
        summary: "Ordenar ideas en bloques reutilizables y codigo legible.",
        lessons: [
          {
            id: "m4l1",
            title: "def: crear funciones utiles",
            duration: "14 min",
            objective: "Agrupar pasos repetidos en una funcion.",
            steps: [
              "Define una funcion saludar(nombre).",
              "Devuelve un texto.",
              "Llamala con distintos nombres.",
            ],
            challenge: "Crea funcion despedir(nombre) y usala.",
            tip: "Definir funcion no ejecuta nada hasta llamarla.",
            code: 'def saludar(nombre):\n    return "Hola " + nombre\n\nprint(saludar("Nico"))\nprint(saludar("Lara"))',
          },
          {
            id: "m4l2",
            title: "Parametros y retorno para resolver problemas",
            duration: "16 min",
            objective: "Enviar datos a una funcion y recuperar resultado.",
            steps: [
              "Crea funcion area_rectangulo(base, altura).",
              "Retorna base * altura.",
              "Muestra el resultado con print.",
            ],
            challenge: "Haz funcion promedio(x, y, z).",
            tip: "Retornar permite reutilizar el resultado en otras cuentas.",
            code: 'def area_rectangulo(base, altura):\n    return base * altura\n\narea = area_rectangulo(8, 3)\nprint("Area:", area)',
          },
          {
            id: "m4l3",
            title: "Funciones pequenas, codigo claro",
            duration: "14 min",
            objective: "Dividir un problema largo en funciones cortas.",
            steps: [
              "Separa ingreso, calculo y salida en funciones distintas.",
              "Pon nombres claros a variables y funciones.",
              "Evita repetir codigo pegando y copiando.",
            ],
            challenge: "Refactoriza un script largo en al menos 3 funciones.",
            tip: "Si una funcion hace demasiadas cosas, separala.",
            code: 'def pedir_numero(texto):\n    return int(input(texto))\n\ndef sumar(a, b):\n    return a + b\n\na = pedir_numero("A: ")\nb = pedir_numero("B: ")\nprint("Total:", sumar(a, b))',
          },
          {
            id: "m4l4",
            title: "Comentarios utiles y DRY basico",
            duration: "14 min",
            objective: "Comentar con sentido y reducir duplicacion.",
            steps: [
              "Agrega un comentario que explique una decision clave.",
              "Quita repeticiones usando una funcion.",
              "Vuelve a leer el codigo para verificar claridad.",
            ],
            challenge: "Convierte dos bloques casi iguales en una sola funcion.",
            tip: "Comenta el por que, no lo obvio del como.",
            code: 'def mostrar_resultado(titulo, valor):\n    # Este formato se usa en todo el programa\n    print(titulo + ":", valor)\n\nmostrar_resultado("Puntaje", 9)\nmostrar_resultado("Nivel", "Inicial")',
          },
        ],
      },
      {
        id: "m5",
        title: "5) Estructuras de datos I y II",
        summary: "Listas, tuplas y diccionarios para manejar mas informacion.",
        lessons: [
          {
            id: "m5l1",
            title: "Listas: crear, agregar y recorrer",
            duration: "16 min",
            objective: "Guardar varios datos en una sola estructura.",
            steps: [
              "Crea lista con materias.",
              "Agrega una materia con append.",
              "Recorre lista con for.",
            ],
            challenge: "Muestra cuantas materias hay con len().",
            tip: "Las listas cambian: puedes agregar, borrar o editar elementos.",
            code: 'materias = ["Matematica", "Robotica", "Lengua"]\nmaterias.append("Ingles")\nfor m in materias:\n    print(m)\nprint("Total:", len(materias))',
          },
          {
            id: "m5l2",
            title: "Listas en problemas reales",
            duration: "16 min",
            objective: "Procesar lista de notas para obtener resultados utiles.",
            steps: [
              "Crea una lista de notas.",
              "Calcula promedio con sum y len.",
              "Muestra mayor y menor nota.",
            ],
            challenge: "Cuenta cuantas notas son >= 7.",
            tip: "Con listas puedes analizar datos sin repetir variables.",
            code: 'notas = [8, 6, 9, 7, 10]\npromedio = sum(notas) / len(notas)\nprint("Promedio:", promedio)\nprint("Mayor:", max(notas), "Menor:", min(notas))',
          },
          {
            id: "m5l3",
            title: "Tuplas: datos que no cambian",
            duration: "12 min",
            objective: "Entender cuando conviene tupla en lugar de lista.",
            steps: [
              "Crea una tupla con coordenadas.",
              "Accede por indice 0 y 1.",
              "Compara con una lista y observa diferencia.",
            ],
            challenge: "Guarda RGB de un color en una tupla e imprimelo.",
            tip: "Tupla = estable; lista = flexible.",
            code: 'coordenada = (120, 45)\nprint("X:", coordenada[0])\nprint("Y:", coordenada[1])',
          },
          {
            id: "m5l4",
            title: "Diccionarios: clave y valor",
            duration: "18 min",
            objective: "Modelar informacion con etiquetas descriptivas.",
            steps: [
              "Crea diccionario alumno con nombre, edad y curso.",
              "Imprime valores por clave.",
              "Actualiza una clave y vuelve a imprimir.",
            ],
            challenge: "Agrega clave 'promedio' y muestra ficha completa.",
            tip: "Diccionario ayuda cuando cada dato tiene etiqueta clara.",
            code: 'alumno = {"nombre": "Luca", "edad": 13, "curso": "1B"}\nprint(alumno["nombre"])\nalumno["edad"] = 14\nprint(alumno)',
          },
        ],
      },
      {
        id: "m6",
        title: "6) Integracion y evaluacion corta",
        summary: "Conectar todo lo aprendido en desafios previos al bloque final.",
        lessons: [
          {
            id: "m6l1",
            title: "Desafio integrador guiado",
            duration: "20 min",
            objective: "Combinar input, condicionales, bucles y funciones en un solo problema.",
            steps: [
              "Construye menu simple de opciones con while.",
              "Usa funcion para cada opcion.",
              "Muestra resultados en pantalla.",
            ],
            challenge: "Agrega opcion extra de estadistica basica.",
            tip: "Si el problema crece, dividir en funciones es obligatorio.",
            code: 'def mostrar_menu():\n    print("1) Saludar")\n    print("2) Salir")\n\nopcion = ""\nwhile opcion != "2":\n    mostrar_menu()\n    opcion = input("Elige: ")\n    if opcion == "1":\n        print("Hola!")',
          },
          {
            id: "m6l2",
            title: "Simulacro de prueba practica",
            duration: "18 min",
            objective: "Entrenar formato de evaluacion corta con tiempo limitado.",
            steps: [
              "Resuelve un ejercicio de variables y operadores.",
              "Resuelve uno de condicionales.",
              "Resuelve uno de listas o funciones.",
            ],
            challenge: "Explica tu solucion en voz alta en 60 segundos.",
            tip: "Primero que funcione, despues mejoras estilo.",
            code: 'numeros = [3, 5, 8, 2]\npares = 0\nfor n in numeros:\n    if n % 2 == 0:\n        pares += 1\nprint("Cantidad de pares:", pares)',
          },
          {
            id: "m6l3",
            title: "Checklist de preparacion final",
            duration: "12 min",
            objective: "Verificar dominio minimo antes de pasar al hardware.",
            steps: [
              "Revisa si dominas if/for/while.",
              "Comprueba que puedes crear y llamar funciones.",
              "Valida manejo basico de listas y diccionarios.",
            ],
            challenge: "Marca tus puntos fuertes y uno a reforzar.",
            tip: "Detectar huecos antes del proyecto ahorra mucho tiempo.",
            code: 'habilidades = ["if", "for", "funciones", "listas"]\nfor h in habilidades:\n    print("Revisar:", h)',
          },
        ],
      },
      {
        id: "m7",
        title: "7) Hardware PyBot (bloque concentrado)",
        summary: "Las 6 clases con placa: conexion, pin, tiempos y control de actuadores.",
        lessons: [
          {
            id: "m7l1",
            title: "Conexion segura y prueba inicial",
            duration: "14 min",
            objective: "Conectar la placa y validar comunicacion sin riesgos.",
            steps: [
              "Conecta por USB y usa el boton Conectar.",
              "Ejecuta un print de prueba para confirmar entorno.",
              "Desconecta correctamente al finalizar.",
            ],
            challenge: "Escribe un mini protocolo de conexion en 3 pasos.",
            tip: "Si algo falla, desconectar y reconectar suele resolver rapido.",
            code: 'print("Iniciando prueba de conexion...")\nprint("Si no hay errores, estamos listos para hardware.")',
          },
          {
            id: "m7l2",
            title: "Salida digital con pin(out)",
            duration: "18 min",
            objective: "Encender y apagar una salida en un patron simple.",
            steps: [
              "Configura pin de salida.",
              "Enciende y apaga con espera.",
              "Repite secuencia en bucle corto.",
            ],
            challenge: "Haz parpadear 5 veces y termina apagado.",
            tip: "Empieza con un pin y cuando funcione, recien agrega mas.",
            code: 'for _ in range(5):\n    pin("out", 2, 1)\n    wait(0.4)\n    pin("out", 2, 0)\n    wait(0.4)',
          },
          {
            id: "m7l3",
            title: "Entrada digital + decisiones",
            duration: "20 min",
            objective: "Leer un pin de entrada y reaccionar con if/else.",
            steps: [
              "Lee estado de un boton o sensor digital.",
              "Si esta activo, enciende una salida.",
              "Si no, manten salida apagada.",
            ],
            challenge: "Agrega contador de activaciones en terminal.",
            tip: "Hardware y logica se entienden mejor con mensajes print claros.",
            code: 'estado = pin("in", 7)\nif estado == 1:\n    pin("out", 2, 1)\n    print("Sensor activo")\nelse:\n    pin("out", 2, 0)\n    print("Sensor inactivo")',
          },
          {
            id: "m7l4",
            title: "PWM / servo basico para control gradual",
            duration: "22 min",
            objective: "Mover de manera gradual (brillo, velocidad o angulo).",
            steps: [
              "Prueba una salida PWM con varios valores.",
              "Observa diferencia entre niveles.",
              "Haz una secuencia suave de subida y bajada.",
            ],
            challenge: "Diseña efecto de respiracion con PWM.",
            tip: "Sube de a poco, prueba y evita saltos bruscos al inicio.",
            code: 'for v in [0, 64, 128, 192, 255, 128, 64, 0]:\n    pin("pwm", 5, v)\n    wait(0.2)',
          },
        ],
      },
      {
        id: "m8",
        title: "8) Proyecto final",
        summary: "Disenar, construir, probar y presentar una solucion propia.",
        lessons: [
          {
            id: "m8l1",
            title: "Diseno del proyecto y plan de pruebas",
            duration: "18 min",
            objective: "Definir objetivo, entradas, salidas y pasos de validacion.",
            steps: [
              "Elige problema real y objetivo concreto.",
              "Haz lista de componentes y funciones necesarias.",
              "Crea plan de pruebas en 5 casos.",
            ],
            challenge: "Incluye al menos una funcion reutilizable y una decision if/else.",
            tip: "Proyecto claro gana tiempo: primero plan, despues codigo.",
            code: 'def objetivo_proyecto():\n    return "Controlar una luz automatica segun sensor"\n\nprint("Proyecto:", objetivo_proyecto())',
          },
          {
            id: "m8l2",
            title: "Entrega, demo y mejora",
            duration: "20 min",
            objective: "Presentar version funcional y proponer una mejora futura.",
            steps: [
              "Muestra funcionamiento base en vivo.",
              "Explica una parte del codigo clave.",
              "Propone una mejora para version 2.",
            ],
            challenge: "Entrega version individual o en pareja segun criterio docente.",
            tip: "No busques perfeccion: busca que funcione y se entienda.",
            code: 'print("Demo final en marcha")\nprint("Version 1 lista para presentar")\nprint("Siguiente mejora: agregar modo nocturno")',
          },
        ],
      },
    ],
  },
  en: {
    badge: "Guided path",
    title: "Python from zero (ages 12-13) + final hardware block",
    subtitle:
      "28 micro lessons across a 16-class plan: strong Python core first, hardware and capstone at the end.",
    modules: [
      {
        id: "m1",
        title: "1) Core basics",
        summary: "First contact with code: print, variables, data types, and error reading.",
        lessons: [
          {
            id: "m1l1",
            title: "Your first useful script",
            duration: "12 min",
            objective: "Run code confidently and read output in the terminal.",
            steps: [
              "Write three print lines with different messages.",
              "Run and check output order.",
              "Edit one line and run again to verify changes.",
            ],
            challenge: "Create a 4-line intro card about yourself.",
            tip: "The fastest learning loop is run, inspect, tweak, run again.",
            code: 'print("Hello, Python class")\nprint("My name is Emma")\nprint("I am 12 years old")\nprint("Today I start coding")',
          },
          {
            id: "m1l2",
            title: "Variables that store meaning",
            duration: "14 min",
            objective: "Use variables to avoid hardcoded repeated values.",
            steps: [
              "Create name, age, and classroom variables.",
              "Print one sentence using all three.",
              "Update values without touching the final print.",
            ],
            challenge: "Add favorite_game and include it in the message.",
            tip: "Clear variable names reduce bugs before they happen.",
            code: 'name = "Emma"\nage = 12\nclassroom = "7A"\nprint("I am", name, "from", classroom, "and I am", age)',
          },
          {
            id: "m1l3",
            title: "Data types you will use every day",
            duration: "14 min",
            objective: "Identify int, float, str, and bool with confidence.",
            steps: [
              "Create one variable of each type.",
              "Print each value with type(value).",
              "Compare your predictions with actual output.",
            ],
            challenge: "Create two more variables and guess their type first.",
            tip: "Knowing type helps you pick valid operations.",
            code: 'count = 5\nscore = 8.5\ntopic = "Robotics"\nready = True\nprint(type(count), type(score), type(topic), type(ready))',
          },
          {
            id: "m1l4",
            title: "Common beginner errors",
            duration: "10 min",
            objective: "Read and fix syntax issues without panic.",
            steps: [
              "Run code with a quote mismatch.",
              "Read the error line carefully.",
              "Fix it and run again.",
            ],
            challenge: "Cause a parenthesis error and repair it.",
            tip: "Errors are feedback, not failure.",
            code: 'print("This line is valid")\n# print("This line has a broken quote)\nprint("Now fixed and running")',
          },
        ],
      },
      {
        id: "m2",
        title: "2) Input, output, and operators",
        summary: "Build interactive scripts, convert values, and compute results.",
        lessons: [
          {
            id: "m2l1",
            title: "Input + print for interactive apps",
            duration: "14 min",
            objective: "Collect user data and generate dynamic messages.",
            steps: [
              "Ask for name and favorite hobby.",
              "Store answers in variables.",
              "Print a custom response.",
            ],
            challenge: "Ask for city too and include it in output.",
            tip: "input returns text, then you decide how to transform it.",
            code: 'name = input("Your name: ")\nhobby = input("Favorite hobby: ")\nprint("Hi", name, "- lets talk about", hobby)',
          },
          {
            id: "m2l2",
            title: "Type conversion that prevents bugs",
            duration: "14 min",
            objective: "Use int(), float(), and str() correctly in real tasks.",
            steps: [
              "Read two numbers using input.",
              "Convert both values to int.",
              "Print sum and average.",
            ],
            challenge: "Also print the absolute difference.",
            tip: "Without conversion, + may join strings instead of adding numbers.",
            code: 'a = int(input("Number 1: "))\nb = int(input("Number 2: "))\nprint("Sum:", a + b)\nprint("Average:", (a + b) / 2)',
          },
          {
            id: "m2l3",
            title: "Arithmetic, comparison, and logic",
            duration: "16 min",
            objective: "Combine math operations with decision conditions.",
            steps: [
              "Create two variables and do basic math.",
              "Compare values with >= and ==.",
              "Combine conditions with and/or.",
            ],
            challenge: "Create a rule for joining a team tryout.",
            tip: "Use = for assignment, == for comparison.",
            code: 'age = 12\npermission = True\nprint("double age:", age * 2)\nprint("age >= 12?", age >= 12)\nprint("can join tryout?", age >= 12 and permission)',
          },
        ],
      },
      {
        id: "m3",
        title: "3) Flow control",
        summary: "Choose paths and repeat actions without copy-paste.",
        lessons: [
          {
            id: "m3l1",
            title: "if / else for two-way decisions",
            duration: "14 min",
            objective: "Use simple branching based on conditions.",
            steps: [
              "Create a grade variable.",
              "Print pass message when grade >= 7.",
              "Print support message otherwise.",
            ],
            challenge: "Change threshold and test behavior.",
            tip: "Colon plus indentation define each branch block.",
            code: 'grade = 8\nif grade >= 7:\n    print("Passed")\nelse:\n    print("Needs practice")',
          },
          {
            id: "m3l2",
            title: "elif for multiple outcomes",
            duration: "16 min",
            objective: "Classify scores into more than two categories.",
            steps: [
              "Create a score variable.",
              "Build if/elif/else with three ranges.",
              "Test with different values.",
            ],
            challenge: "Add a perfect-score category.",
            tip: "Check higher thresholds first.",
            code: 'score = 86\nif score >= 90:\n    print("Excellent")\nelif score >= 70:\n    print("Good")\nelse:\n    print("Keep training")',
          },
          {
            id: "m3l3",
            title: "for + range patterns",
            duration: "16 min",
            objective: "Repeat steps using controlled numeric loops.",
            steps: [
              "Loop from 1 to 5 with range.",
              "Print lap index each turn.",
              "Change boundaries and observe output.",
            ],
            challenge: "Build the multiplication table of 6.",
            tip: "range(1, 6) stops at 5.",
            code: 'for i in range(1, 6):\n    print("Lap", i)\n\nfor i in range(1, 11):\n    print("6 x", i, "=", 6 * i)',
          },
          {
            id: "m3l4",
            title: "while, break, continue, pass",
            duration: "18 min",
            objective: "Control loops with conditions and safe exits.",
            steps: [
              "Build a while counter.",
              "Use continue to skip one value.",
              "Use break to stop early.",
            ],
            challenge: "Count to 10 but skip 4.",
            tip: "Always design while with a clear stop condition.",
            code: 'n = 0\nwhile n < 10:\n    n += 1\n    if n == 4:\n        continue\n    if n == 9:\n        break\n    print(n)',
          },
        ],
      },
      {
        id: "m4",
        title: "4) Functions + coding habits",
        summary: "Write reusable blocks and improve readability from day one.",
        lessons: [
          {
            id: "m4l1",
            title: "def: build reusable tools",
            duration: "14 min",
            objective: "Turn repeated code into reusable function blocks.",
            steps: [
              "Create greet(name) function.",
              "Return a message string.",
              "Call it with different values.",
            ],
            challenge: "Create goodbye(name) and call both.",
            tip: "Function definition and function call are two separate steps.",
            code: 'def greet(name):\n    return "Hello " + name\n\nprint(greet("Noah"))\nprint(greet("Mila"))',
          },
          {
            id: "m4l2",
            title: "Parameters and return values",
            duration: "16 min",
            objective: "Pass inputs to functions and capture outputs.",
            steps: [
              "Create rectangle_area(base, height).",
              "Return base * height.",
              "Print result in main flow.",
            ],
            challenge: "Write average(x, y, z).",
            tip: "Returning values makes composition and testing easier.",
            code: 'def rectangle_area(base, height):\n    return base * height\n\narea = rectangle_area(8, 3)\nprint("Area:", area)',
          },
          {
            id: "m4l3",
            title: "Small functions, cleaner scripts",
            duration: "14 min",
            objective: "Split long tasks into focused functions.",
            steps: [
              "Separate input, processing, and output.",
              "Use names that explain intent.",
              "Remove repeated code blocks.",
            ],
            challenge: "Refactor one long script into 3+ functions.",
            tip: "If one function is doing everything, split it.",
            code: 'def ask_number(label):\n    return int(input(label))\n\ndef add(a, b):\n    return a + b\n\na = ask_number("A: ")\nb = ask_number("B: ")\nprint("Total:", add(a, b))',
          },
          {
            id: "m4l4",
            title: "Useful comments and DRY basics",
            duration: "14 min",
            objective: "Document intent and avoid duplication patterns.",
            steps: [
              "Add one comment that explains a decision.",
              "Replace duplicate prints with one helper function.",
              "Re-read code and simplify wording.",
            ],
            challenge: "Merge two similar blocks into one reusable function.",
            tip: "Comment decisions, not obvious syntax.",
            code: 'def show_result(title, value):\n    # Shared display format used across the app\n    print(title + ":", value)\n\nshow_result("Score", 9)\nshow_result("Level", "Starter")',
          },
        ],
      },
      {
        id: "m5",
        title: "5) Data structures I and II",
        summary: "Use lists, tuples, and dictionaries to model richer data.",
        lessons: [
          {
            id: "m5l1",
            title: "Lists: create, append, iterate",
            duration: "16 min",
            objective: "Manage multiple values inside one variable.",
            steps: [
              "Create a subjects list.",
              "Append one new subject.",
              "Loop through the list with for.",
            ],
            challenge: "Print total items using len().",
            tip: "Lists are mutable, so they are great for growing datasets.",
            code: 'subjects = ["Math", "Robotics", "Language"]\nsubjects.append("English")\nfor s in subjects:\n    print(s)\nprint("Total:", len(subjects))',
          },
          {
            id: "m5l2",
            title: "Lists in practical problems",
            duration: "16 min",
            objective: "Compute summary metrics from a list of values.",
            steps: [
              "Create a grades list.",
              "Compute average with sum/len.",
              "Find max and min values.",
            ],
            challenge: "Count how many grades are >= 7.",
            tip: "One list can replace many single-purpose variables.",
            code: 'grades = [8, 6, 9, 7, 10]\navg = sum(grades) / len(grades)\nprint("Average:", avg)\nprint("Max:", max(grades), "Min:", min(grades))',
          },
          {
            id: "m5l3",
            title: "Tuples for fixed data",
            duration: "12 min",
            objective: "Understand immutable grouped values.",
            steps: [
              "Create a coordinate tuple.",
              "Read positions by index.",
              "Compare tuple behavior to list behavior.",
            ],
            challenge: "Store one RGB color in a tuple and print it.",
            tip: "Tuple means stable structure that should not be edited.",
            code: 'point = (120, 45)\nprint("X:", point[0])\nprint("Y:", point[1])',
          },
          {
            id: "m5l4",
            title: "Dictionaries with key-value pairs",
            duration: "18 min",
            objective: "Use labeled fields to represent real entities.",
            steps: [
              "Create a student dictionary.",
              "Print values by key.",
              "Update one field and print again.",
            ],
            challenge: "Add average_grade and show full record.",
            tip: "Dictionaries shine when values need clear labels.",
            code: 'student = {"name": "Luca", "age": 13, "group": "7B"}\nprint(student["name"])\nstudent["age"] = 14\nprint(student)',
          },
        ],
      },
      {
        id: "m6",
        title: "6) Integration + short practical assessment",
        summary: "Bridge all Python foundations before moving into hardware classes.",
        lessons: [
          {
            id: "m6l1",
            title: "Guided integration challenge",
            duration: "20 min",
            objective: "Combine input, branching, loops, and functions in one mini app.",
            steps: [
              "Create a simple text menu with while.",
              "Implement one function per menu action.",
              "Display results clearly in terminal.",
            ],
            challenge: "Add one extra menu option with simple statistics.",
            tip: "Integrated tasks reveal what you truly understand.",
            code: 'def show_menu():\n    print("1) Greet")\n    print("2) Exit")\n\nchoice = ""\nwhile choice != "2":\n    show_menu()\n    choice = input("Choose: ")\n    if choice == "1":\n        print("Hello!")',
          },
          {
            id: "m6l2",
            title: "Short practical test simulation",
            duration: "18 min",
            objective: "Practice assessment-style problems under light time pressure.",
            steps: [
              "Solve one variables/operators question.",
              "Solve one conditional flow question.",
              "Solve one list or function question.",
            ],
            challenge: "Explain your solution in under one minute.",
            tip: "Correct first, elegant second.",
            code: 'numbers = [3, 5, 8, 2]\neven_count = 0\nfor n in numbers:\n    if n % 2 == 0:\n        even_count += 1\nprint("Even values:", even_count)',
          },
          {
            id: "m6l3",
            title: "Readiness checklist before hardware",
            duration: "12 min",
            objective: "Confirm minimum skills before the final hardware block.",
            steps: [
              "Verify confidence with if/for/while.",
              "Verify function creation and calls.",
              "Verify list and dictionary basics.",
            ],
            challenge: "Mark one weak topic and plan how to improve it.",
            tip: "Closing gaps now makes hardware classes smoother.",
            code: 'skills = ["if", "for", "functions", "lists"]\nfor s in skills:\n    print("Review:", s)',
          },
        ],
      },
      {
        id: "m7",
        title: "7) PyBot hardware block",
        summary: "Concentrated hardware stage: connect board, read/write pins, and build control logic.",
        lessons: [
          {
            id: "m7l1",
            title: "Safe connection and first check",
            duration: "14 min",
            objective: "Connect hardware and verify stable communication.",
            steps: [
              "Connect board over USB and press Connect.",
              "Run a terminal check script.",
              "Disconnect properly after test.",
            ],
            challenge: "Write a 3-step connection checklist for your team.",
            tip: "When connection fails, restart in a calm, repeatable order.",
            code: 'print("Starting connection check...")\nprint("No error messages means we are ready.")',
          },
          {
            id: "m7l2",
            title: "Digital output with pin(out)",
            duration: "18 min",
            objective: "Switch an output on/off in a repeatable pattern.",
            steps: [
              "Use one output pin.",
              "Turn it on, wait, then off.",
              "Repeat in a short loop.",
            ],
            challenge: "Blink exactly five times, ending in OFF state.",
            tip: "Master one pin first, scale later.",
            code: 'for _ in range(5):\n    pin("out", 2, 1)\n    wait(0.4)\n    pin("out", 2, 0)\n    wait(0.4)',
          },
          {
            id: "m7l3",
            title: "Digital input + decision logic",
            duration: "20 min",
            objective: "Read an input and react with if/else behavior.",
            steps: [
              "Read a button or digital sensor value.",
              "If active, turn on an output.",
              "Else keep it off.",
            ],
            challenge: "Count sensor activations in terminal output.",
            tip: "Print messages help you debug hardware state changes.",
            code: 'state = pin("in", 7)\nif state == 1:\n    pin("out", 2, 1)\n    print("Sensor active")\nelse:\n    pin("out", 2, 0)\n    print("Sensor idle")',
          },
          {
            id: "m7l4",
            title: "PWM or servo basic control",
            duration: "22 min",
            objective: "Apply smooth level changes for light, speed, or angle.",
            steps: [
              "Send several PWM levels.",
              "Observe response differences.",
              "Build a smooth up/down sequence.",
            ],
            challenge: "Create a breathing-style light effect.",
            tip: "Small increments keep behavior stable and predictable.",
            code: 'for v in [0, 64, 128, 192, 255, 128, 64, 0]:\n    pin("pwm", 5, v)\n    wait(0.2)',
          },
        ],
      },
      {
        id: "m8",
        title: "8) Final project",
        summary: "Plan, implement, test, and present a working solution.",
        lessons: [
          {
            id: "m8l1",
            title: "Project design and test plan",
            duration: "18 min",
            objective: "Define scope, required pieces, and validation criteria.",
            steps: [
              "Choose a real-world goal.",
              "List inputs, outputs, and functions needed.",
              "Draft five test cases.",
            ],
            challenge: "Include at least one reusable function and one if/else branch.",
            tip: "Strong planning saves debugging time later.",
            code: 'def project_goal():\n    return "Build an automatic light controller"\n\nprint("Goal:", project_goal())',
          },
          {
            id: "m8l2",
            title: "Demo, delivery, and next iteration",
            duration: "20 min",
            objective: "Present v1 clearly and propose one meaningful improvement.",
            steps: [
              "Run a live functional demo.",
              "Explain one key code section.",
              "Propose a v2 improvement.",
            ],
            challenge: "Deliver solo or pair mode based on teacher choice.",
            tip: "A clear, working v1 beats an unfinished complex plan.",
            code: 'print("Final demo running")\nprint("Version 1 submitted")\nprint("Next iteration: add night mode")',
          },
        ],
      },
    ],
  },
};

